# Generated by Django 3.0.8 on 2020-10-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I', models.CharField(max_length=232)),
                ('II', models.CharField(max_length=232)),
                ('III', models.CharField(max_length=232)),
                ('IV', models.CharField(max_length=232)),
                ('MOLECULE', models.CharField(max_length=232)),
                ('PRODUCT', models.CharField(max_length=232)),
                ('PACKAGE', models.CharField(max_length=232)),
                ('CORPORATION', models.CharField(max_length=232)),
                ('MANUF_TYPE', models.CharField(max_length=232)),
                ('FORMULATION', models.CharField(max_length=232)),
                ('STRENGTH', models.CharField(max_length=232)),
                ('AMOUNT', models.IntegerField()),
                ('UNIT', models.CharField(max_length=232)),
                ('PERIOD', models.CharField(max_length=232)),
                ('DATE', models.DateField()),
            ],
        ),
    ]
